"Карты":
  - UnityProject/Assets/**/*.unity

"Карта: SquareStation":
  - UnityProject/Assets/Scenes/MainStations/SquareStation.unity

"Карта: PogStation":
  - UnityProject/Assets/Scenes/MainStations/PogStation.unity

"Карта: FallStation":
  - UnityProject/Assets/Scenes/MainStations/FallStation.unity

"Карта: OutpostStation":
  - UnityProject/Assets/Scenes/MainStations/OutpostStation.unity

"Карта: BoxStation":
  - UnityProject/Assets/Scenes/MainStations/BoxStationV1.unity

"Документация":
  - docs/**/*

"Спрайты":
  - UnityProject/Assets/Textures/**/*.png
  - UnityProject/Assets/Textures/**/*.PNG
  - AssetLibrary/**/*.png
  - AssetLibrary/**/*.PNG

"UI":
  - UnityProject/Assets/Scripts/UI/**/*
  - UnityProject/Assets/Scenes/UI/**/*

"Статус: проверка":
  - /*
